name: 'BundleMon'
description: 'A free open-source tool that helps you to monitor your bundle size on every commit and alerts you on changes.'
author: 'LironEr'
branding:
  icon: 'activity'
  color: 'green'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  bundlemon-args:
    required: false
    description: 'Optional args for BundleMon cli. Example: --subProject "some-name"'
  bundlemon-version:
    required: false
    description: 'BundleMon cli version, if not specified will use latest'
  working-directory:
    required: false
    description: 'The working directory'
  fail-on-error:
    required: false
    description: 'Should fail on error'